---
name: test_build

on:
  push:
    paths:
      - "**.py"
      - "setup.cfg"
      - "MANIFEST.in"
      - "pyproject.toml"
      - "requirements.txt"
      - ".github/workflows/test_build.yaml"
  pull_request:
    paths:
      - "**.py"
      - "setup.cfg"
      - "MANIFEST.in"
      - "pyproject.toml"
      - "requirements.txt"
      - ".github/workflows/test_build.yaml"

jobs:
  test_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install requirements
        run: if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Install build tools
        run: pip install setuptools wheel build
      - name: Get Version in setup.py
        run: python3 setup.py --version
      - name: Get Version in Src
        run: python3 -c "import icoextract ; print(icoextract.__version__) ; print(icoextract.__file__)"
      - name: Run build
        run: python3 -m build
      - name: Get Wheel File Path
        id: getwheelfile
        shell: bash
        run: echo "::set-output name=wheelfile::$(find "dist" -type f -name "*.whl")"
      - name: Test pip install of wheel
        shell: bash
        run: pip install ${{ steps.getwheelfile.outputs.wheelfile }}
      - name: Get Version in Pip Install
        run: python3 -c "import os ; os.chdir('..') ; import icoextract ; print(icoextract.__version__) ; print(icoextract.__file__)"
